#启动方式 nohup java   -Dspring.profiles.active=dev -jar synchronius-1.0.jar >  log.erp 2>&1 &
server:
  port: 8081
  compression:
    enabled: true
  connection-timeout: 3000

dubbo:
  name: mk-dubbo-store-server-springboot
  zookeeper: zookeeper://127.0.0.1:2181

swagger:
  host: local.dev.com

